-- MySQL Script generated by MySQL Workbench
-- Tue May 12 14:45:38 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto_integrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_integrador` DEFAULT CHARACTER SET utf8 ;
USE `projeto_integrador` ;

-- -----------------------------------------------------
-- Table `projeto_integrador`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`USUARIOS` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `matricula` VARCHAR(20) NOT NULL,
  `tipo_usuario` ENUM('ALUNO', 'SECRETARIO', 'ADMINISTRADOR') NOT NULL,
  `ativo` TINYINT NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  PRIMARY KEY (`id_usuarios`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`CURSOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`CURSOS` (
  `id_cursos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_cursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`TURMAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`TURMAS` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `id_curso` INT NOT NULL,
  `turno` ENUM('MANHA', 'TARDE', 'NOITE') NOT NULL,
  `aluno-turma_idaluno-turma` INT NOT NULL,
  `CURSOS_id_cursos` INT NOT NULL,
  PRIMARY KEY (`id_turma`, `aluno-turma_idaluno-turma`, `CURSOS_id_cursos`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `fk_TURMAS_CURSOS1_idx` (`CURSOS_id_cursos` ASC),
  CONSTRAINT `fk_TURMAS_CURSOS1`
    FOREIGN KEY (`CURSOS_id_cursos`)
    REFERENCES `projeto_integrador`.`CURSOS` (`id_cursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`DOCUMENTOS_EMITIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`DOCUMENTOS_EMITIDOS` (
  `id_documentos_emitidos` INT NOT NULL AUTO_INCREMENT,
  `id_solicitacao` INT NOT NULL,
  `id_tipo` INT NOT NULL,
  `arquivo` VARCHAR(100) NOT NULL,
  `data_emissão` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `USUARIOS_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_documentos_emitidos`, `USUARIOS_id_usuarios`),
  INDEX `fk_DOCUMENTOS_EMITIDOS_USUARIOS_idx` (`USUARIOS_id_usuarios` ASC),
  CONSTRAINT `fk_DOCUMENTOS_EMITIDOS_USUARIOS`
    FOREIGN KEY (`USUARIOS_id_usuarios`)
    REFERENCES `projeto_integrador`.`USUARIOS` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`CONFIGURACOES_SISTEMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`CONFIGURACOES_SISTEMA` (
  `id_configuracao_sistema` INT NOT NULL AUTO_INCREMENT,
  `prazo_padrao_dias` INT NULL,
  PRIMARY KEY (`id_configuracao_sistema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`SOLICITACOES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`SOLICITACOES` (
  `id_solicitacao` INT NOT NULL AUTO_INCREMENT,
  `numero_protocolo` VARCHAR(20) NULL,
  `id_tipo` INT NOT NULL,
  `justificativa` TEXT NOT NULL,
  `prioridade` ENUM('COMUM', 'URGENTE') NOT NULL,
  `status` ENUM('RECEBIDO', 'EM_ANALISE', 'EM-CONFECCAO', 'AGUARDANDO_ASSINATURA', 'DEFERIDO', 'INDEFERIDO', 'FINALIZADO') NOT NULL,
  `data_solicitacao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `prazo_final` DATETIME NULL,
  `data_finalização` DATETIME NULL,
  `USUARIOS_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_solicitacao`, `USUARIOS_id_usuarios`),
  UNIQUE INDEX `numero_protocolo_UNIQUE` (`numero_protocolo` ASC),
  INDEX `fk_SOLICITACOES_USUARIOS1_idx` (`USUARIOS_id_usuarios` ASC),
  CONSTRAINT `fk_SOLICITACOES_USUARIOS1`
    FOREIGN KEY (`USUARIOS_id_usuarios`)
    REFERENCES `projeto_integrador`.`USUARIOS` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`ANEXOS_SOLICITACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`ANEXOS_SOLICITACAO` (
  `id_anexos_solicitacao` INT NOT NULL AUTO_INCREMENT,
  `id_solicitacao` INT NOT NULL,
  `arquivo` VARCHAR(100) NULL,
  `data_upload` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `SOLICITACOES_id_solicitacao` INT NOT NULL,
  PRIMARY KEY (`id_anexos_solicitacao`, `SOLICITACOES_id_solicitacao`),
  INDEX `fk_ANEXOS_SOLICITACAO_SOLICITACOES1_idx` (`SOLICITACOES_id_solicitacao` ASC),
  CONSTRAINT `fk_ANEXOS_SOLICITACAO_SOLICITACOES1`
    FOREIGN KEY (`SOLICITACOES_id_solicitacao`)
    REFERENCES `projeto_integrador`.`SOLICITACOES` (`id_solicitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`MOVIMENTACOES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`MOVIMENTACOES` (
  `id_movimentacoes` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('RECEBIDO', 'EM_ANALISE', 'EM-CONFECCAO', 'AGUARDANDO_ASSINATURA', 'DEFERIDO', 'INDEFERIDO', 'FINALIZADO') NOT NULL,
  `observacao` TEXT NOT NULL,
  `data_movimentacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `SOLICITACOES_id_solicitacao` INT NOT NULL,
  PRIMARY KEY (`id_movimentacoes`, `SOLICITACOES_id_solicitacao`),
  INDEX `fk_MOVIMENTACOES_SOLICITACOES1_idx` (`SOLICITACOES_id_solicitacao` ASC),
  CONSTRAINT `fk_MOVIMENTACOES_SOLICITACOES1`
    FOREIGN KEY (`SOLICITACOES_id_solicitacao`)
    REFERENCES `projeto_integrador`.`SOLICITACOES` (`id_solicitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`NOTIFICACOES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`NOTIFICACOES` (
  `id_notificacao` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `mensagem` TEXT NOT NULL,
  `tipo` ENUM('RECEBIDO', 'EM_ANALISE', 'EM-CONFECCAO', 'AGUARDANDO_ASSINATURA', 'DEFERIDO', 'INDEFERIDO', 'FINALIZADO') NOT NULL,
  `lida` TINYINT NULL,
  `data_envio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `SOLICITACOES_id_solicitacao` INT NOT NULL,
  PRIMARY KEY (`id_notificacao`, `SOLICITACOES_id_solicitacao`),
  INDEX `fk_NOTIFICACOES_SOLICITACOES1_idx` (`SOLICITACOES_id_solicitacao` ASC),
  CONSTRAINT `fk_NOTIFICACOES_SOLICITACOES1`
    FOREIGN KEY (`SOLICITACOES_id_solicitacao`)
    REFERENCES `projeto_integrador`.`SOLICITACOES` (`id_solicitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`ALUNO_TURMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`ALUNO_TURMA` (
  `USUARIOS_id_usuarios` INT NOT NULL,
  `TURMAS_id_turma` INT NOT NULL,
  PRIMARY KEY (`USUARIOS_id_usuarios`, `TURMAS_id_turma`),
  INDEX `fk_USUARIOS_has_TURMAS_has_USUARIOS_USUARIOS1_idx` (`USUARIOS_id_usuarios` ASC),
  INDEX `fk_USUARIOS_has_TURMAS_has_USUARIOS_TURMAS1_idx` (`TURMAS_id_turma` ASC),
  CONSTRAINT `fk_USUARIOS_has_TURMAS_has_USUARIOS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_id_usuarios`)
    REFERENCES `projeto_integrador`.`USUARIOS` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOS_has_TURMAS_has_USUARIOS_TURMAS1`
    FOREIGN KEY (`TURMAS_id_turma`)
    REFERENCES `projeto_integrador`.`TURMAS` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`LOGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`LOGS` (
  `id_logs` INT NOT NULL AUTO_INCREMENT,
  `tabela_afetada` VARCHAR(50) NOT NULL,
  `id_registro` INT NOT NULL,
  `acao` VARCHAR(20) NOT NULL,
  `descricao` TEXT NOT NULL,
  `data_log` DATETIME NOT NULL,
  `USUARIOS_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_logs`, `USUARIOS_id_usuarios`),
  INDEX `fk_LOGS_USUARIOS1_idx` (`USUARIOS_id_usuarios` ASC),
  CONSTRAINT `fk_LOGS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_id_usuarios`)
    REFERENCES `projeto_integrador`.`USUARIOS` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;